[project]
name = "spencerwoo-com"
version = "0.1.0"
description = "Spencer Woo's Site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-awesome-pages-plugin>=2.10",
    "mkdocs-glightbox>=0.5",
    "mkdocs-material[imaging]>=9.6",
    "mkdocs-rss-plugin>=1.17",
]
